spring.application.name=projeto-web


# Configuração do Kafka (Local)
spring.kafka.bootstrap-servers=localhost:9092
# Transforma nosso Record/DTO em JSON para mandar pela rede
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Transforma o JSON de volta em Record/DTO quando lê a mensagem
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Diz ao Kafka qual pacote de classes ele tem permissão para converter
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.projeto_web.dto


# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/loja-vestuario

# E-mail (Gmail como exemplo)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
spring.mail.password=sua-senha-de-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Kafka consumer group
spring.kafka.consumer.group-id=grupo-email
spring.kafka.consumer.auto-offset-reset=earliest