spring.application.name=projeto-web


# Configuração do Kafka (Local)
spring.kafka.bootstrap-servers=localhost:9092
# Transforma nosso Record/DTO em JSON para mandar pela rede
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Transforma o JSON de volta em Record/DTO quando lê a mensagem
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Diz ao Kafka qual pacote de classes ele tem permissão para converter
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.projeto_web.dto